const dataArray = [
  {
    descricao: "Batata, inglesa, frita",
    tipo: "Verduras, hortaliças e derivados",
    energia: 267,
    proteina: 5,
    lipideos: 13.1,
    carboidrato: 35.6,
    fibra: 8.1,
  },
  {
    descricao: "Batata, inglesa, sauté",
    tipo: "Verduras, hortaliças e derivados",
    energia: 68,
    proteina: 1.3,
    lipideos: 0.9,
    carboidrato: 14.1,
    fibra: 1.4,
  },
  {
    descricao: "Berinjela, cozida",
    tipo: "Verduras, hortaliças e derivados",
    energia: 19,
    proteina: 0.7,
    lipideos: 0.1,
    carboidrato: 4.5,
    fibra: 2.5,
  },
  {
    descricao: "Berinjela, crua",
    tipo: "Verduras, hortaliças e derivados",
    energia: 20,
    proteina: 1.2,
    lipideos: 0.1,
    carboidrato: 4.4,
    fibra: 2.9,
  },
  {
    descricao: "Beterraba, cozida",
    tipo: "Verduras, hortaliças e derivados",
    energia: 32,
    proteina: 1.3,
    lipideos: 0.1,
    carboidrato: 7.2,
    fibra: 1.9,
  },
  {
    descricao: "Beterraba, crua",
    tipo: "Verduras, hortaliças e derivados",
    energia: 49,
    proteina: 1.9,
    lipideos: 0.1,
    carboidrato: 11.1,
    fibra: 3.4,
  },
  {
    descricao: "Biscoito, polvilho doce",
    tipo: "Verduras, hortaliças e derivados",
    energia: 438,
    proteina: 1.3,
    lipideos: 12.2,
    carboidrato: 80.5,
    fibra: 1.2,
  },
  {
    descricao: "Brócolis, cozido",
    tipo: "Verduras, hortaliças e derivados",
    energia: 25,
    proteina: 2.1,
    lipideos: 0.5,
    carboidrato: 4.4,
    fibra: 3.4,
  },
  {
    descricao: "Pão, milho, forma",
    tipo: "Cereais e derivados",
    energia: 292,
    proteina: 8.3,
    lipideos: 3.1,
    carboidrato: 56.4,
    fibra: 4.3,
  },
  {
    descricao: "Pão, trigo, forma, integral",
    tipo: "Cereais e derivados",
    energia: 253,
    proteina: 9.4,
    lipideos: 3.7,
    carboidrato: 49.9,
    fibra: 6.9,
  },
  {
    descricao: "Pão, trigo, francês",
    tipo: "Cereais e derivados",
    energia: 300,
    proteina: 8,
    lipideos: 3.1,
    carboidrato: 58.6,
    fibra: 2.3,
  },
  {
    descricao: "Pão, trigo, sovado",
    tipo: "Cereais e derivados",
    energia: 311,
    proteina: 8.4,
    lipideos: 2.8,
    carboidrato: 61.5,
    fibra: 2.4,
  },
  {
    descricao: "Pastel, de carne, cru",
    tipo: "Cereais e derivados",
    energia: 289,
    proteina: 10.7,
    lipideos: 8.8,
    carboidrato: 42,
    fibra: 1,
  },
  {
    descricao: "Pastel, de carne, frito",
    tipo: "Cereais e derivados",
    energia: 388,
    proteina: 10.1,
    lipideos: 20.1,
    carboidrato: 43.8,
    fibra: 1,
  },
  {
    descricao: "Pastel, de queijo, cru",
    tipo: "Cereais e derivados",
    energia: 308,
    proteina: 9.9,
    lipideos: 9.6,
    carboidrato: 45.9,
    fibra: 1.1,
  },
  {
    descricao: "Pastel, de queijo, frito",
    tipo: "Cereais e derivados",
    energia: 422,
    proteina: 8.7,
    lipideos: 22.7,
    carboidrato: 48.1,
    fibra: 0.9,
  },
];

export { dataArray };
